# Generated by Django 6.0.2 on 2026-02-26 12:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='missionorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionorder',
            name='payment_provider',
            field=models.CharField(blank=True, default='stripe', max_length=30),
        ),
        migrations.AddField(
            model_name='missionorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='missionorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non paye'), ('requires_action', 'Paiement en cours'), ('paid', 'Paye'), ('failed', 'Paiement echoue'), ('refunded', 'Rembourse')], default='unpaid', max_length=20),
        ),
    ]
